cookie:
  expiry_days: 30
  key: abc
  name: def
credentials:
  usernames:
    admin:
      email: fachryikhsal890@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Administrator
      last_name: Administrator
      logged_in: False # Will be managed automatically
      password: Eias2025# # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
oauth2: # Optional
  google: # Follow instructions: https://developers.google.com/identity/protocols/oauth2
    client_id: # To be filled
    client_secret: # To be filled
    redirect_uri: # URL to redirect to after OAuth2 authentication
  microsoft: # Follow instructions: https://learn.microsoft.com/en-us/graph/auth-register-app-v2
    client_id: # To be filled
    client_secret: # To be filled
    redirect_uri: # URL to redirect to after OAuth2 authentication
    tenant_id: # To be filled
pre-authorized: # Optional
  emails:
  - melsby@gmail.com
api_key: # Optional - register to receive a free API key: https://stauthenticator.com